{{- template "common.deployment" (list . "activiti.notifications.deployment") -}}
{{- define "activiti.notifications.deployment" -}}
spec:
  template:
    spec:
      initContainers:
      {{- if .Values.postgres.enabled }}
        - name: wait-for-postgresql
          image: {{ .Values.init.container.image | quote }}
          imagePullPolicy: {{ .Values.init.container.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ .Release.Name }}-{{ .Values.postgres.name }} {{ .Values.postgres.port }}; do
                  sleep 2;
              done;
              echo 'PostgreSQL OK ✓'
      {{- end }}
      {{- if .Values.rabbitmq.enabled }}
        - name: wait-for-rabbitmq
          image: {{ .Values.init.container.image | quote }}
          imagePullPolicy: {{ .Values.init.container.imagePullPolicy }}
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ include "rabbitmq-name" . }} {{ .Values.rabbitmq.port | default 5672 }}; do
                  sleep 2;
              done;
              echo 'RabbitMq OK ✓'
      {{- end }}
      {{- if .Values.extraInitContainers }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- end }}
{{- end -}}
