# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# Application 
global:
  config: 
    domain: "192.168.99.100.nip.io" 
    tls: # true | false
    prefix: # commmon domain prefix, i.e. activiti
  rabbitmq:
    host:
      value: ""
    username:
      value: guest
    password:
      value: guest
  keycloak:
    url: # "http{{ if $.Values.global.config.tls }}s{{ end }}://activiti-keycloak.{{ .Values.global.config.domain }}/auth"
    host: # "activiti-keycloak.{{ .Release.Name }}.{{ .Values.global.config.domain }}"
    path: # /auth 
    name: keycloak
    service:
      type: http
      port: 80
  gateway: 
    host: # "activiti-cloud-gateway.{{ .Release.Name }}.{{ .Values.global.config.domain }}"
    tlsSecret: # tls-{{ .Release.Name }}-activiti-cloud-gateway
    # global annotations to be added to all service ingresses
    annotations: {}

db:
  uri: ""
  name: querypostgresql
  password: query
  port: 5432
  generateDdl: false
  ddlAuto: none

javaOpts:
  xmx: 1768m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90

## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key

image:
  repository: docker.io/activiti/activiti-cloud-notifications-graphql
  tag: 7.1.69
  pullPolicy: IfNotPresent
  
service:
  name: activiti-cloud-notifications
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    
resources:
  limits:
    memory: 2048Mi
    cpu: 1
  requests:
    cpu: "200m"
    memory: 512Mi
probePath: '{{ .Values.ingress.path }}/actuator/health'
livenessProbe:
  initialDelaySeconds: 140
  periodSeconds: 15
  timeoutSeconds: 20
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
terminationGracePeriodSeconds: 20

ingress:
  ## Set to true to enable ingress record generation
  enabled: true
  path: /notifications
  tls: # overrides .Values.global.gateway.tls  
  tlsSecret: # overrides .Values.global.gateway.tlsSecret  
  hostName: # overrides .Values.global.gateway.host
  actuator: 
    enabled: true
    path: /actuator
  graphiql: 
    enabled: true
    path: /graphiql
  web:
    enabled: true
    path: /graphql
  ws: 
    enabled: true
    path: /ws/graphql
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'Access-Control-Allow-Origin: $http_origin';
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"   
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "activiti-cloud-notifications-graphql-route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/session-cookie-path: "{{ .Values.ingress.path }}"
  

    
